#!/usr/bin/env python3

from interactive_markers.interactive_marker_server import *
from interactive_markers.menu_handler import *
from visualization_msgs.msg import *

import numpy as np
import rospy

from interactive_marker_utils import (
    create_waypoint_marker,
    SetLocalizationCallback,
    NavigateCallback
)

# Color values for markers
SELECTED_R = 0.05
SELECTED_G = 0.45
SELECTED_B = 0.98
UNSELECTED_R = 0.45
UNSELECTED_G = 0.06
UNSELECTED_B = 0.67

localization = None

def main():
    rospy.init_node("spot_graphnav_markers", anonymous=True)
    server = InteractiveMarkerServer("navigation_waypoints")

    ##############################
    # Dummy markers for testing
    marker1 = create_waypoint_marker("marker1")
    marker2 = create_waypoint_marker("marker2")

    server.insert(marker2, lambda feedback: feedback, reference_frame="base_link", position=[1, 0, 0.3])
    server.insert(marker1, lambda feedback: feedback, reference_frame="base_link", position=[-1, 0, 0.3])
    ##############################

    # TODO subscribe to marker pose update topic

    # Add menu to markers
    mh = MenuHandler()

    mh.insert("Set localization", callback=SetLocalizationCallback())
    mh.insert("Navigate to", callback=NavigateCallback())

    ##############################
    # Dummy markers
    mh.apply(server, "marker1")
    mh.apply(server, "marker2")
    ##############################

    server.applyChanges()
    rospy.spin()


if __name__ == "__main__":
    main()
