#!/usr/bin/env python3

import logging
import time 
import sys
import os

from spot_driver.spot_wrapper import SpotWrapper
from bosdyn.client.math_helpers import SE3Pose
from quaternion import from_euler_angles, quaternion
import numpy as np

# before executing, we assume our users have made the following environment variables in their os: BOSDYN_CLIENT_USERNAME, BOSDYN_CLIENT_PASSWORD, BOSDYN_CLIENT_IP
# To make an environment variable, do something like export <variable-name> = '<value>', or have a bash script 

if __name__=='__main__':
    '''
    NOTE: This script test the WorldObjectHandler class without requiring 
    any ros specific code. The wrapper could be used with other pure python 
    code.
    ''' 
    FORMAT = '%(message)s'
    logging.basicConfig(format=FORMAT)
    logger = logging.getLogger("rosout")
    logger.debug('Starting code.')

    spot_wrapper = SpotWrapper(os.getenv('BOSDYN_CLIENT_USERNAME'), 
                               os.getenv('BOSDYN_CLIENT_PASSWORD'), 
                               os.getenv('BOSDYN_CLIENT_IP'),  # WIFI
                                logger=logger,
                                estop_timeout=9.0,)

    logger.setLevel('DEBUG')
    
    logger.debug('Powering on...')
    spot_wrapper.getLease(hijack=True)
    spot_wrapper.power_on()

    logger.debug('Standing...')
    spot_wrapper.ensure_arm_power_and_stand()

    logger.debug('Moving hand to a pose...')
    
    quat = from_euler_angles(0, 0, 0)
    position = [1.0, 0.0, 0.0]
    
    results = spot_wrapper.hand_pose(position, 
                                     [quat.w, quat.x, quat.y, quat.z],
                                     duration=3.0, gripper_opening=1.0)
    logger.debug(f'Results: {results}')
   
    # time.sleep(5)
    spot_wrapper.safe_power_off()
    spot_wrapper.releaseLease()


    logger.debug(f'Success!!!')
