#!/usr/bin/env python3


import rospy
from find_grasp_point_utils.FindGraspPoint import FindGraspPoint



def main():
        
        rospy.init_node('find_grasp_point', anonymous=True)
        grap_point_searcher = FindGraspPoint()
        grap_point_searcher._server.start()
        try:
            rospy.spin()
        except KeyboardInterrupt:
            print("Shutting down")

if __name__ == '__main__':
    main()