#!/usr/bin/env python3


import rospy


def main():
        
        rospy.init_node('spot_demo', anonymous=True)
        try:
            rospy.spin()
        except KeyboardInterrupt:
            print("Shutting down")

if __name__ == '__main__':
    main()